### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by NastjaD** [iquidus/explorer#106]
Hey guys,

after setting everything up like its shown in the readme I am getting the following errors:

`node --stack-size=10000 bin/instance

/root/blockexplorer/explorer/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:757
      catch(err) { process.nextTick(function() { throw err}); }
                                                       ^
TypeError: Cannot read property 'name' of undefined
    at Server.equals (/root/blockexplorer/explorer/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1057:16)
    at State.isPrimary (/root/blockexplorer/explorer/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset_state.js:71:39)
    at State.update (/root/blockexplorer/explorer/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset_state.js:404:69)
    at /root/blockexplorer/explorer/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset.js:975:27
    at /root/blockexplorer/explorer/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:756:13
    at Callbacks.emit (/root/blockexplorer/explorer/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/root/blockexplorer/explorer/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/root/blockexplorer/explorer/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
`

node -v
v0.10.48

mongo -version
MongoDB shell version: 2.6.10

mongod --version
db version v2.6.10
2017-10-28T13:07:51.591+0200 git version: nogitversion
2017-10-28T13:07:51.591+0200 OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

**Comment by erfan007p** [comment]
Your mongod didn't run properly

**Comment by NastjaD** [comment]
I can see that mongod is running - I also restarted it a couple of times. Did I missed a paramter specified in the mongodb settings?

**Comment by TheHolyRoger** [comment]
Dup of https://github.com/iquidus/explorer/issues/56
