### ISSUE TITLE
Trying to reindex and getting error Script already running..

### ISSUE THREAD

**Issue by ctgiant** [iquidus/explorer#11]
I have the script running from the crontab for index update and market.  I have stopped the cronjobs and am trying to run the script for reindexing from the root folder of my explorer install by running: 

node scripts/sync.js index reindex

but all it outputs is "Script already running.."

I have checked my server for sync.js running using ps aux | grep "sync.js" and there are no entries there.
So how do I stop the script from running so that I can reindex if I have already disabled it in the crontab?

**Comment by iquidus** [comment]
Hi ctgiant, 

This is covered in the known issues area of the readme, although it is intended behaviour to some extent. When the sync.js script runs with the index option it creates a lockfile tmp/index.pid, if this file exists, the script will not run, and will give you the already running message. This is to prevent the script running multiple times during the initial index (e.g if initial index takes 40minutes but cron is set to execute script every 1 minute).

simply remove the tmp/index.pid file and you will be able to run the script. Normally this happens when the script exits cleanly, but in case of being killed early it gets left behind.

**Comment by ctgiant** [comment]
I can't believe I missed that.  I must have read right over it.  Thanks for the response.

**Comment by mddeepak** [comment]
node scripts/sync.js index update
script launched with pid: 6952
C:\explorer\explorer\lib\database.js:642
              lib.syncLoop(block.tx.length, function (subloop) {
                                    ^

TypeError: Cannot read property 'length' of undefined
    at C:\explorer\explorer\lib\database.js:642:37
    at Request._callback (C:\explorer\explorer\lib\explorer.js:107:14)
    at Request.self.callback (C:\explorer\explorer\node_modules\request\request.
js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\explorer\explorer\node_modules\request\request.js
:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\explorer\explorer\node_modules\request\re
quest.js:965:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


please give me any solution.
