### ISSUE TITLE
Cryptopia Market Sync issue

### ISSUE THREAD

**Issue by CryptvJet** [iquidus/explorer#123]
xyz:~/explorer# nodejs scripts/sync.js market reindex
script launched with pid: 6657

/explorer/lib/markets/cryptopia.js:53
        if (body.Success == true) {
                ^
TypeError: Cannot read property 'Success' of undefined
    at Request._callback (/explorer/lib/markets/cryptopia.js:53:17)
    at self.callback (/explorer/node_modules/request/request.js:187:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.onRequestError (/explorer/node_modules/request/request.js:813:8)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1389:19)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:982:10)
    at CleartextStream.read [as _read] (tls.js:469:13)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
_______

The Cryptopia market is not syncing, it is showing old data.

I tried to do it manually and got an error message.

**Comment by cryptoj** [comment]
No longer getting error.

Seems to have resolved itself.

**Comment by TheHolyRoger** [comment]
Exchange markets are no longer hardcoded thanks to @uaktags - https://github.com/iquidus/explorer/commit/2be23e2f8f0e446943518303efef95ca964c59a9
