### ISSUE TITLE
Error: Invalid params, response status code: 401

### ISSUE THREAD

**Issue by bigzim** [iquidus/explorer#126]
Hello, 

Trying my best to setup iquidus with a new blockchain, i have setup iquidus a few times before with no problems, first time i have ever got an error, not sure what the problem is. Any help is much appreciated.

GET /ext/getlasttxs/0.00000001?_=1515338052945 200 6ms - 11b
{ Error: Invalid params, response status code: 401
    at IncomingMessage.<anonymous> (/explorer/node_modules/bitcoin/lib/jsonrpc.js:79:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: -32602 }
GET /api/getdifficulty 200 262ms - 39b
{ Error: Invalid params, response status code: 401
    at IncomingMessage.<anonymous> (/explorer/node_modules/bitcoin/lib/jsonrpc.js:79:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: -32602 }
GET /api/getnetworkhashps 200 260ms - 39b
{ Error: Invalid params, response status code: 401
    at IncomingMessage.<anonymous> (/explorer/node_modules/bitcoin/lib/jsonrpc.js:79:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: -32602 }
GET /api/getconnectioncount 200 263ms - 39b
{ Error: Invalid params, response status code: 401
    at IncomingMessage.<anonymous> (/explorer/node_modules/bitcoin/lib/jsonrpc.js:79:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: -32602 }
GET /api/getblockcount 200 263ms - 39b

**Comment by syyyn** [comment]
What was the fix for this?

**Comment by Ecrypty** [comment]
how can i solve this error, have the same issue

**Comment by bunbunbunbunbunny** [comment]
How solve this ?

**Comment by go140point6** [comment]
401 is "Access Forbidden".  You need to make sure your rpcusername and password is correct and if you have any special characters in your rpcpassword, remove them.  Probably was the # sign in mine, but I just removed them all.  Might be a way to escape them but wasn't worth the effort.  Once I removed my special characters and restarted my coin daemon, my 401 Forbidden went away and I was able to run ```sync.js index update``` without issue.
