### ISSUE TITLE
Is this error from the coin Blockchain?

### ISSUE THREAD

**Issue by ob1100** [iquidus/explorer#13]
I get an error when running  "node  scripts/sync.js index check" (this was working for a week without a problem).  

tx not found: 6be77ef48cd15abaaeddb3f79357342082ab56a3de5ca923548e5dc2141ad4b6

TypeError: Cannot read property 'length' of undefined
    at /home/BE/dashlite/lib/explorer.js:309:42
    at Request._callback (/home/BE/dashlite/lib/explorer.js:84:14)
    at Request.self.callback (/home/BE/dashlite/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/BE/dashlite/node_modules/request/request.js:985:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/BE/dashlite/node_modules/request/request.js:936:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

And this is when I run:
node  scripts/sync.js index reindex

1071: 9c971c5207d0e074183c68a988b64b8dc06bc2a64c35dedd6a90a2ca591958cb

TypeError: Cannot read property 'length' of undefined
    at /home/BE/dashlite/lib/explorer.js:309:42
    at Request._callback (/home/BE/dashlite/lib/explorer.js:84:14)
    at Request.self.callback (/home/BE/dashlite/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/BE/dashlite/node_modules/request/request.js:985:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/BE/dashlite/node_modules/request/request.js:936:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by ob1100** [comment]
Problem was on my side had to reindex coin with the -txindex
