### ISSUE TITLE
index update gives error.. can anyone help with this please

### ISSUE THREAD

**Issue by pawan0413** [iquidus/explorer#142]
```
root@tgbcloud-Virtual-Machine:/home/explorer# node scripts/sync.js index reindex
script launched with pid: 38868
index cleared (reindex)
/home/explorer/lib/database.js:642
              lib.syncLoop(block.tx.length, function (subloop) {
                                   ^

TypeError: Cannot read property 'length' of undefined
    at /home/explorer/lib/database.js:642:36
    at Request._callback (/home/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/home/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/explorer/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

```

**Comment by pawan0413** [comment]
And npm console shows this error

```
GET /ext/getlasttxs/0.00000001?_=1518376374267 200 4ms - 11b
{ [Error: connect ECONNREFUSED 103.212.71.89:8332]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '103.212.71.89',
  port: 8332 }
GET /api/getblockcount 200 2ms - 39b
{ [Error: connect ECONNREFUSED 103.212.71.89:8332]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '103.212.71.89',
  port: 8332 }
GET /api/getconnectioncount 200 1ms - 39b
{ [Error: connect ECONNREFUSED 103.212.71.89:8332]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '103.212.71.89',
  port: 8332 }
GET /api/getblockhash?height=0 200 1ms - 39b
{ [Error: connect ECONNREFUSED 103.212.71.89:8332]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '103.212.71.89',
  port: 8332 }
GET /api/getblock?hash=There%20was%20an%20error.%20Check%20your%20console. 200 2ms - 39b


```

**Comment by pawan0413** [comment]
anyway.. I have solved the issue.. 

Thanks guys..

**Comment by bfinleyui** [comment]
Thanks for sharing your solution.

👎

**Comment by leegod** [comment]
@pawan0413  how you solved? plz same error here.

**Comment by lukepighetti** [comment]
@pawan0413 Please share your solution.

**Comment by lukepighetti** [comment]
Hi everyone. In my situation, I was trying to start *coind as a daemon. It was giving me a "reindex" error and crashing. My solution was to run it as a normal process and make sure everything was working well before trying to connect explorer.
