### ISSUE TITLE
ran explorer for quite a few coins succesfully. then for one i get this error.

### ISSUE THREAD

**Issue by regtable** [iquidus/explorer#148]
```{ Error: No information available about transaction
    at /home/usr/flapexplorer/node_modules/bitcoin/lib/jsonrpc.js:99:19
    at Array.forEach (native)
    at IncomingMessage.<anonymous> (/home/usr/flapexplorer/node_modules/bitcoin/lib/jsonrpc.js:96:15)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: -5 }
```
this happens first run on clean database. there after it just loops block #1 and thats all it does. i have tried different settings to no avail. thanks in advance

**Comment by regtable** [comment]
fixed. was the network hash part. i had it down as getinfo believing the coin was a pow/pos hybrid which had the pos removed but still in code. turns out changing this to coinbase fixed it :-)
