### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by aitorp6** [iquidus/explorer#154]
hi

I'm having the following problem when I want to update The database. The proeblem is always with the same block. Any ideas?

`/root/explorer/lib/explorer.js:290
        module.exports.is_unique(arr_vout, vout[i].scriptPubKey.addresses[0], function(unique, index) {
                                                                         ^

TypeError: Cannot read property '0' of undefined
    at module.exports.syncLoop.arr_vout.(anonymous function).amount (/root/explorer/lib/explorer.js:290:74)
    at Object.loop.next (/root/explorer/lib/explorer.js:189:18)
    at Object.module.exports.syncLoop (/root/explorer/lib/explorer.js:205:10)
    at Object.module.exports.prepare_vout (/root/explorer/lib/explorer.js:284:20)
    at /root/explorer/lib/database.js:141:17
    at /root/explorer/lib/explorer.js:392:14
    at Object.loop.next (/root/explorer/lib/explorer.js:194:24)
    at /root/explorer/lib/explorer.js:383:22
    at Object.module.exports.convert_to_satoshi (/root/explorer/lib/explorer.js:25:12)
    at /root/explorer/lib/explorer.js:381:30
    at /root/explorer/lib/explorer.js:263:14
    at Object.loop.next (/root/explorer/lib/explorer.js:177:19)
    at /root/explorer/lib/explorer.js:258:14
    at Object.loop.next (/root/explorer/lib/explorer.js:189:18)
    at /root/explorer/lib/explorer.js:260:14
    at Object.loop.next (/root/explorer/lib/explorer.js:189:18)
`

**Comment by pivxslimjim** [comment]
@aitorp6 How'd you fix?
