### ISSUE TITLE
using livecoin api

### ISSUE THREAD

**Issue by avandurmen0001** [iquidus/explorer#165]
TypeError: Cannot read property 'last' of undefined
    at /home/ace/explorer/lib/database.js:594:37
    at Query.callback (/home/ace/explorer/node_modules/mongoose/lib/query.js:2008:7)
    at /home/ace/explorer/node_modules/kareem/index.js:177:19
    at /home/ace/explorer/node_modules/kareem/index.js:109:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by TheHolyRoger** [comment]
Exchange markets are no longer hardcoded thanks to @uaktags - https://github.com/iquidus/explorer/commit/2be23e2f8f0e446943518303efef95ca964c59a9
