### ISSUE TITLE
Unable to connect to explorer API

### ISSUE THREAD

**Issue by bylucy** [iquidus/explorer#166]
Hello
I have such a problem,
i created block explorer and when I connect with my coin writes an error: 
root@newera:~/explorer# node scripts/sync.js index reindex
Script already running..
root@newera:~/explorer# node scripts/sync.js index reindex
script launched with pid: 29567
Unable to connect to explorer API
index cleared (reindex)

TypeError: Cannot read property 'length' of undefined
at /root/explorer/lib/database.js:642:36
at Request._callback (/root/explorer/lib/explorer.js:107:14)
at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
at Request.EventEmitter.emit (events.js:98:17)
at Request. (/root/explorer/node_modules/request/request.js:1044:10)
at Request.EventEmitter.emit (events.js:95:17)
at IncomingMessage. (/root/explorer/node_modules/request/request.js:965:12)
at IncomingMessage.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:920:16
at process._tickCallback (node.js:415:13)

newera.conf
rpcuser=newerarpc 
rpcpassword=mypassword
rpcallowip=178.62.226.109 
server=1
txindex=1

blockexplorer - http://178.62.226.109:49111

I use server ubuntu 14.04 digitalocean.com
please explain what the problem is

**Comment by voxcon** [comment]
You haven't defined your rpcport in your config file. 
Do so by adding this line:

rpcport=THE_RPC_PORT_YOUR_WALLET_USES

**Comment by bylucy** [comment]
i adding port
rpcuser=newerarpc 
rpcpassword=9WuqjsZ7s2VRZi7BwfKqmgRta5RpmuzMurGR4Z5vs9PZ 
rpcallowip=178.62.226.109
rpcport=49110 
server=1
txindex=1

writes an error:
Error: An error occurred while setting up the RPC port 49110 for listening on IPv4: bind: Address already in use
