### ISSUE TITLE
Explorer index update issue

### ISSUE THREAD

**Issue by braravind** [iquidus/explorer#176]
Hello,
 I have user this explorer. when i start it works fine and block data showing properly. But now it not updating blocks. "not working index update".

showing given below error message. please provide any solution for that.

Error:

root@ubuntu:~/explorer# node scripts/sync.js index update
script launched with pid: 14229
/root/explorer/lib/database.js:642
              lib.syncLoop(block.tx.length, function (subloop) {
                                    ^

TypeError: Cannot read property 'length' of undefined
    at /root/explorer/lib/database.js:642:37
    at Request._callback (/root/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

Thank You!
Aravind

**Comment by pivxslimjim** [comment]
Having a similar isssue:

/home/explorer/lib/database.js:648
              lib.syncLoop(block.tx.length, function (subloop) {
                                   ^

TypeError: Cannot read property 'length' of undefined
    at /home/explorer/lib/database.js:648:36
    at Request._callback (/home/explorer/lib/explorer.js:116:14)
    at Request.self.callback (/home/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/explorer/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by pivxslimjim** [comment]
I synced up maybe 70-75% of the blocks and then this started. I've been forcesyncing blocks but I would like to try to investigate this..

**Comment by newdaikicoin** [comment]
Hello @pivxslimjim 
What solution for that issue. If you have any solution please help for that.

Thank You!
Aravind

**Comment by pivxslimjim** [comment]
I have found none-yet. I also haven't tried 100% to fix this, hoping other people have fixed this already..

**Comment by pivxslimjim** [comment]
Heres some insight-
The tx format has changed on some blocks. See examples:
(Block 951418)  https://pivx.support/toolbox/tx.php?tx=33327ec2b4f599929398304887f5269492020f2fa1e81427848e9704d2c5df7a

(Block 400000) https://pivx.support/toolbox/tx.php?tx=8d1bb8c704125e0a9311cb57446c78de94d1e8f03837f5d635108bfbef26841b

It seems the different formatting could trigger an error? Idk

**Comment by pivxslimjim** [comment]
{ [Error: Block height out of range] code: -8 }
GET /api/getblockhash?height=-2 200 2862ms - 39b
GET /api/getdifficulty 200 1266ms - 15b
{ [Error: Block not found] code: -5 }

I see this here too... (Npm start)

**Comment by pivxslimjim** [comment]
Think I might have an idea how to fix. monitor my issue #177

**Comment by mddeepak** [comment]
node scripts/sync.js index update
script launched with pid: 6952
C:\explorer\explorer\lib\database.js:642
              lib.syncLoop(block.tx.length, function (subloop) {
                                    ^

TypeError: Cannot read property 'length' of undefined
    at C:\explorer\explorer\lib\database.js:642:37
    at Request._callback (C:\explorer\explorer\lib\explorer.js:107:14)
    at Request.self.callback (C:\explorer\explorer\node_modules\request\request.
js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\explorer\explorer\node_modules\request\request.js
:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\explorer\explorer\node_modules\request\re
quest.js:965:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


Please help me.

**Comment by braravind** [comment]
Hello mddeepak ,

Add txindex=1 in your config or run daemon with txindex option. 
and reindex the node where explorer hit

Thanks!

**Comment by mddeepak** [comment]
@braravind  thank you so much

But I am getting new error when compile start npm

{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }

please help 
Thanks

**Comment by ReeCore** [comment]
Hi seems you have incorrect ports or you trying with one explorer already runing, check with top

**Comment by uaktags** [comment]
OP's issue was due to format changes in the coind, but he provided a url example rather than showing the differences for future investigation. Since it can't be seen, I'm closing the comment.
