### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by pivxslimjim** [iquidus/explorer#177]
Info:
- Had no sync issues until about ~800k blocks out of 1.1m blocks
- Config file is good
- Tried other fixes proposed on the issues tab
- Been forcesyncing since

(ciquidus) 
----------------------------------------------------------------

/home/explorer/lib/database.js:648
lib.syncLoop(block.tx.length, function (subloop) {
^

TypeError: Cannot read property 'length' of undefined
at /home/explorer/lib/database.js:648:36
at Request._callback (/home/explorer/lib/explorer.js:116:14)
at Request.self.callback (/home/explorer/node_modules/request/request.js:187:22)
at emitTwo (events.js:87:13)
at Request.emit (events.js:172:7)
at Request. (/home/explorer/node_modules/request/request.js:1044:10)
at emitOne (events.js:77:13)
at Request.emit (events.js:169:7)
at IncomingMessage. (/home/explorer/node_modules/request/request.js:965:12)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:905:12)
at nextTickCallbackWith2Args (node.js:441:9)
at process._tickCallback (node.js:355:17)

**Comment by pivxslimjim** [comment]
GET /api/getblockcount 200 4220ms - 7b
GET /api/getconnectioncount 200 1954ms - 2b
{ [Error: Block height out of range] code: -8 }
GET /api/getblockhash?height=-3 200 637ms - 39b
{ [Error: Block not found] code: -5 }
GET /api/getblock?hash=There%20was%20an%20error.%20Check%20your%20console. 200 36ms - 39b

-------
Observing npm start , when running the index update script seems to generat ethis error consistently

**Comment by pivxslimjim** [comment]
Update:
Replacing the code provided by blakey a few days later seems to have started updating my block index again. #118 However, as my explorer is on block 951000, the indexing seems to have started on block 63000-ish. Weird, will keep trying..

**Comment by pivxslimjim** [comment]
Blakey's fix with some other change I've made seems to have fixed my issue.

**Comment by nicovs** [comment]
@pivxslimjim care to share what other changes you made?

**Comment by leegod** [comment]
How you solved?
