### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by psionin** [iquidus/explorer#18]
Hi, I like this explorer and have been using it with SmartCoin.

I set it up again and after syncing fine and working, there is an error that happens when trying to do an 'index update' about 24 hours after the last update (without running a cron job).

The following error occurs:

```

TypeError: Cannot read property 'length' of undefined
    at /home/www/explorer/lib/database.js:622:36
    at Request._callback (/home/www/explorer/lib/explorer.js:106:14)
    at Request.self.callback (/home/www/explorer/node_modules/request/request.js:121:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/home/www/explorer/node_modules/request/request.js:985:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/home/www/explorer/node_modules/request/request.js:936:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by iquidus** [comment]
Hi there,

This error is often caused if running the coin daemon without the -txindex flag, or if the explorer is not actually connected to the daemon. 

If you join the #iquidus channel in the Jumbucks slack (http://slack.getjumbucks.com), I can help you resolve this issue much easier :)
