### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by GabrielLeonte** [iquidus/explorer#184]
Someone help ? Ubuntu Server 16.04  32BIT

> explorer@1.6.1 start /home/gabi/explorer
> node --stack-size=10000 ./bin/cluster

Starting cluster with pid: 7524
{ Error: socket hang up
    at createHangUpError (_http_client.js:336:15)
    at Socket.socketOnEnd (_http_client.js:429:23)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19) code: 'ECONNRESET' }
GET /api/getdifficulty 200 126ms - 39b
{ Error: socket hang up
    at createHangUpError (_http_client.js:336:15)
    at Socket.socketOnEnd (_http_client.js:429:23)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19) code: 'ECONNRESET' }
GET /api/getnetworkhashps 200 22ms - 39b
{ Error: socket hang up
    at createHangUpError (_http_client.js:336:15)
    at Socket.socketOnEnd (_http_client.js:429:23)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19) code: 'ECONNRESET' }
GET /api/getconnectioncount 200 21ms - 39b
{ Error: socket hang up
    at createHangUpError (_http_client.js:336:15)
    at Socket.socketOnEnd (_http_client.js:429:23)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19) code: 'ECONNRESET' }
GET /api/getblockcount 200 20ms - 39b
GET /ext/summary 304 278ms

**Comment by adslinfosoft** [comment]
I got the same problem. I was using work rpcport....

For resolving this define rpcport in your conf file on coin wallet. And same should be in Settings.json file of explorer (cp ./settings.json.template ./settings.json), This will solve the problem.

server=1
rpcuser=user
rpcpassword=password
rpcallowip=127.0.0.1
rpcport=YOUR_PORT
txindex=1

Same should be in explorer/settings.json

// wallet settings
  "wallet": {
    "host": "localhost",
    "port": YOUR_PORT,
    "user": "user",
    "pass": "password"
  },

**Comment by Zafford** [comment]
If I do that, I get "Error: An error occurred while setting up the RPC port <port> for listening on IPv4: bind: Address already in use" when I start my coind

**Comment by uaktags** [comment]
Then your port for rpcbind is set to something that's already being used. Find out what it is and kill it or change you coind's rpcport to a new port in the coin's conf file. And then add it to your settings.json. This isn't an iquidus problem as much as it is a userconfig problem with your coin.

**Comment by uaktags** [comment]
netstat -plant | grep <port> on linux
netstat -ano | findstr <port> on windows
These should help you identify what's on that port by giving you the process id (and name on linux) and then you can stop or change your config and restart.
