### ISSUE TITLE
Error update blockchain cryptocurrency

### ISSUE THREAD

**Issue by jgalode** [iquidus/explorer#185]
**Hello, after an reindex and update with the command `node scripts/sync.js index reindex`/ `node scripts/sync.js index update` had this**
![screen](https://user-images.githubusercontent.com/19157935/39085453-bace7fb8-4582-11e8-8c44-188473d0a4ad.PNG)

```
/var/www/pricecoin/lib/explorer.js:344
          module.exports.syncLoop(tx.vout.length, function (loop) {
                                          ^

TypeError: Cannot read property 'length' of undefined
    at /var/www/pricecoin/lib/explorer.js:344:43
    at Request._callback (/var/www/pricecoin/lib/explorer.js:114:14)
    at Request.self.callback (/var/www/pricecoin/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/pricecoin/node_modules/request/request.js:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/pricecoin/node_modules/request/request.js:965:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by jgalode** [comment]
problem resolved in the ".conf" daemon configuration file add `txindex=1`

**Comment by uaktags** [comment]
Issue is resolved by OP.
