### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by hinosisi** [iquidus/explorer#187]
Error: bind EADDRINUSE null:3001
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at cb (net.js:1336:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:766:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
events.js:160
      throw er; // Unhandled 'error' event

**Comment by Rav3nPL** [comment]
EADDRINUSE means You have port 3001 in use...

**Comment by uaktags** [comment]
Closing due to issue already being explained and resolved.
