### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by QUAR-Network** [iquidus/explorer#215]
trying to run    ```node scripts/sync.js index reindex```   and keep getting this does anyone know what it means

```
index cleared (reindex)
/root/explorer/lib/database.js:642
              lib.syncLoop(block.tx.length, function (subloop) {
                                   ^

TypeError: Cannot read property 'length' of undefined
    at /root/explorer/lib/database.js:642:36
    at Request._callback (/root/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)



```

**Comment by MagnaCoinX** [comment]
Having the exact same issue.

**Comment by omurkaangokyar** [comment]
1-) Open your .conf file and add txindex=1,than stop coin and restart with -daemon.
2-) Open your explorer's settings.json file and find //wallet settings section. The port must be same with your coin rpc port. The user and password must be exactly the same with your .conf file rpc username and rpc password. 
3-) Stop explorer and start again.

**Comment by TheHolyRoger** [comment]
Dup of https://github.com/iquidus/explorer/issues/56
