### ISSUE TITLE
how to fix, Error: Method not found

### ISSUE THREAD

**Issue by 631250005** [iquidus/explorer#223]
GET /api/getnetworkhashps 200 6ms - 39b
GET /api/getconnectioncount 200 2ms - 2b
GET /api/getblockcount 200 3ms - 6b
GET /ext/summary 200 23ms - 136b
GET /ext/getlasttxs/0.00000001?_=1537413762077 200 13ms - 11b
GET /api/getdifficulty 200 5ms - 91b
{ Error: Method not found
    at /root/exp1/node_modules/bitcoin/lib/jsonrpc.js:99:19
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (/root/exp1/node_modules/bitcoin/lib/jsonrpc.js:96:15)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19) code: -32601 }

**Comment by 631250005** [comment]
i use that demon.
https://github.com/ChristianSommer/BIZ

**Comment by 631250005** [comment]
everything didnt work, but "Difficulty"  works

**Comment by 631250005** [comment]
fixed

**Comment by k7n2g** [comment]
Could you show the fix for this one, please would be appreciated
