### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by everycrypto** [iquidus/explorer#228]
{ Error: Problem parsing JSON response from server
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/bitcoin/lib/jsonrpc.js:83:17)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: -32603 }
GET /api/getpeerinfo 200 29ms - 39b

**Comment by cryptomaxsun** [comment]
npm install

**Comment by everycrypto** [comment]
TypeError: Cannot read property 'proof-of-work' of undefined
    at /root/explorer/routes/index.js:287:19
    at Request._callback (/root/explorer/lib/explorer.js:79:14)
    at self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/root/explorer/node_modules/request/request.js:813:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
