### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by D3m0nKingx** [iquidus/explorer#268]
```js
explorer@demon:~/explorer$ nodejs scripts/peers.js
/home/explorer/explorer/scripts/peers.js:29
        var address = body[i].addr.split(':')[0];
                                   ^

TypeError: Cannot read property 'split' of undefined
    at /home/explorer/explorer/scripts/peers.js:29:36
    at Object.next (/home/explorer/explorer/lib/explorer.js:189:18)
    at Object.syncLoop (/home/explorer/explorer/lib/explorer.js:205:10)
    at Request._callback (/home/explorer/explorer/scripts/peers.js:27:11)
    at Request.self.callback (/home/explorer/explorer/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/explorer/explorer/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/explorer/explorer/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
```

**Comment by Jenova7** [comment]
same issue

**Comment by D3m0nKingx** [comment]
@Jenova7 I've actually determined the reason for this type of error occurring is because the explorer isn't actually running, therefore the script can't execute.

So be sure it is up by running this script:
```bash
cd path/to/iquidus/directory; pm2 delete all; rm -v tmp/*; sleep 1 && pm2 start -i max bin/cluster --name "Explorer"
```
**pm2** is a process manager that will execute the bin/cluster script and make sure it's always running.

You can install pm2 using npm:

`sudo npm i -g pm2`

Also be sure mongodb is running and setup correctly per the README instructions.

**Comment by D3m0nKingx** [comment]
Closing, issue resolved.
