### ISSUE TITLE
 Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by leegod** [iquidus/explorer#283]
root@vmi265048:~/explorer# node scripts/sync.js index reindex
script launched with pid: 25104
Unable to connect to explorer API
index cleared (reindex)
/root/explorer/lib/database.js:642
              lib.syncLoop(block.tx.length, function (subloop) {
                                   ^

TypeError: Cannot read property 'length' of undefined
    at /root/explorer/lib/database.js:642:36
    at Request._callback (/root/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

I tried everything solutions found google. 
rpcport and .conf and match it at settings.json, restart, revise code at explorer.js 341 line...

Nothing works. 

My daemon, I ran by ./mycoind -daemon -reindex -txindex 
but like 10-20 mins later after running still its getblockcount returns 0 now. 
Is this normal?

Anyway, how can I solve above explorer's length problem?

**Comment by leegod** [comment]
So while after waiting more, coind started to sync, and then explorer's sync.js started to works. But while updating blocks, there are many tx.vout............ block, is this because I revised explorer.js 341 line with codes provided by in this issue board?

**Comment by uaktags** [comment]
My guess is there's any issue with the data that is returned by the daemon and parsed by the npm modules.

Atleast in terms of the original error, if you were still having that, I would suggest the following to see for yourself what is wrong:

https://github.com/iquidus/explorer/blob/30f91a05c5cd1b83c721652c1807232ab9727ebc/lib/database.js#L641
```
 if (block) {
console.log(block) //I would add this line to see what block is, which was provided on L640 by explorer.js#get_block
lib.syncLoop(block.tx.length, function (subloop) {
```
Obviously though, this is a moot point already if you've gotten past this.

**Comment by TheHolyRoger** [comment]
Dup of https://github.com/iquidus/explorer/issues/56
