### ISSUE TITLE
Explorer not populating block details, only difficulty is shown

### ISSUE THREAD

**Issue by fabioganga** [iquidus/explorer#284]
Hi,

I am having a weird problem. The block explorer seems to be working fine, but it is only showing the difficulty and the network hash (hence connection to the wallet must occur).

No error when issuing the command to index update and index reindex either, yet I see no info on the blocks or transactions.

What can I do? 

Thanks for your help!

**Comment by uaktags** [comment]
You say no error when running ``node scripts/sync.js index update``, but are you getting output at all? Specifically you should be getting two things happening:

Your explorer's running log (after running npm start) should start showing you calls to /api/getrawtransation.
Your other terminal window, where you're running the sync update, should be showing you blocks that it hits.

What in all, are you seeing in your terminals?

**Comment by fabioganga** [comment]
Hi @uaktags and thanks a lot for your reply.

I am getting this error when running node scripts/sync.js index update

> script launched with pid: 14184
/root/explorer/lib/database.js:642
              lib.syncLoop(block.tx.length, function (subloop) {
                                    ^

TypeError: Cannot read property 'length' of undefined
    at /root/explorer/lib/database.js:642:37
    at Request._callback (/root/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:965:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Thanks a lot!

**Comment by uaktags** [comment]
Can you put a ``console.log(block)``on line 642?
So 642-643 should say
```
console.log(block);
lib.syncLoop(block.tx.length, function (subloop) {
```
then re-run

**Comment by uaktags** [comment]
Basically, the theory is that the block isn't parsed correctly and we need to know what the value is that's causing it to fail. Specifically the error is that the block's json output doesn't include a "tx" parameter which is why `.length` doesn't exist. This tells me that block isn't actually a block but something else (possibly a string or some other malformed/unexpected object).

**Comment by TheHolyRoger** [comment]
Dup of #56
