### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by streetcrypto7** [iquidus/explorer#288]
ubuntu@vultr:~/explorer$ node scripts/peers.js
/home/ubuntu/explorer/scripts/peers.js:67
          var address = body[i].addr.split(':')[0];
                                     ^

TypeError: Cannot read property 'split' of undefined
    at lib.syncLoop.db.get_peers.i (/home/ubuntu/explorer/scripts/peers.js:67:38)
    at Object.next (/home/ubuntu/explorer/lib/explorer.js:391:18)
    at Object.syncLoop (/home/ubuntu/explorer/lib/explorer.js:409:10)
    at Request._callback (/home/ubuntu/explorer/scripts/peers.js:65:13)
    at Request.self.callback (/home/ubuntu/explorer/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ubuntu/explorer/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/explorer/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by uaktags** [comment]
Hmm, body[i].addr isn't a string that can be split. Looks like you're having an issue with:
http://127.0.0.1:' + settings.port + '/api/getpeerinfo
so my guess is you don't have "npm start" running in another window/screen.

Also, I may be having a moment, but there's not 67 lines in peers.js so that's kinda weird. 


Please confirm for me that you have ``npm start`` running in another screen/window (iquidus 1.6.x requires the explorer to be running) and then rerun this. Also verify that you're using official iqudius and not a fork (ciquidus, diquius, or even my own as that may change the answer/investigation).

If issue is still present, go to https://github.com/iquidus/explorer/blob/bf99bb56eb4f0437c59d54a424882c2f839ca521/scripts/peers.js#L29 and add a new line to ``console.log(body[i])``. This way we can see what is in the body at that specific point (should be an individual peer). If that fails, go either further back to ``console.log(body)`` so we can see what's being returned by getpeerinfo.

**Comment by streetcrypto7** [comment]
@uaktags Thanks for the advice, I've implemented the fix.
