### ISSUE TITLE
"Cannot read property 'length' of undefined" error from scripts/sync.js

### ISSUE THREAD

**Issue by kamronk** [iquidus/explorer#29]
Hello!

I seem to be getting this error when trying to update the transaction db in mongo

root@ubuntu-512mb-nyc3-01:~/explorer# `node scripts/sync.js index update`

```
script launched with pid: 14834
error on this? There was an error. Check your console.

TypeError: Cannot read property 'length' of undefined
    at /root/explorer/lib/database.js:629:36
    at Request._callback (/root/explorer/lib/explorer.js:106:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:121:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:985:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:936:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

This was found in the tmux screen I started npm in

```
> explorer@1.6.1 start /root/explorer
> node --stack-size=10000 ./bin/cluster

Starting cluster with pid: 14805
GET /api/getblockcount 200 13ms - 6b
GET /api/getconnectioncount 200 3ms - 1b
{ [Error: Block number out of range.] code: -1 }
GET /api/getblockhash?height=-8 200 4ms - 39b
{ [Error: Block not found] code: -5 }
GET /api/getblock?hash=There%20was%20an%20error.%20Check%20your%20console. 200 21ms - 39b
```

I've gone through other Closed issues here but am not able to find something relating to this error. Possibly does this mean all transactions have been synced? It was working for a bit prior to getting this error (or atleast it seemed to be working, printing lots to the console as far as tx's it was finding and syncing)

Please let me know if there is any other information I can provide here to be more helpful in getting some help 

Any/all help would be appreciated, Thank you! :)

**Comment by newmight2015** [comment]
node scripts/sync.js index reindex then node scripts/sync.js index update

**Comment by iquidus** [comment]
also check you have txindex=1 set in your coins .config or are launching the coin daemon with the -txindex flag.

**Comment by followtheart** [comment]
Exactly!            -txindex works for me。

**Comment by MineChuteDev** [comment]
I'm having the same issue, however txindex=1 is in my config file.  I get the error with both reindex and update mode.  Also should not that all blocks show as 0 however I can search for block number / height.

reindex
TypeError: Cannot read property 'length' of undefined
    at /home/masterop/explorer/lib/database.js:628:36
    at Request._callback (/home/masterop/explorer/lib/explorer.js:106:14)
    at Request.self.callback (/home/masterop/explorer/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/masterop/explorer/node_modules/request/request.js:985:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/masterop/explorer/node_modules/request/request.js:936:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)

update
TypeError: Cannot read property 'length' of undefined
    at /home/masterop/explorer/lib/database.js:628:36
    at Request._callback (/home/masterop/explorer/lib/explorer.js:106:14)
    at Request.self.callback (/home/masterop/explorer/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/masterop/explorer/node_modules/request/request.js:985:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/masterop/explorer/node_modules/request/request.js:936:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)


Thanks for any help

**Comment by rixon** [comment]
I'm had this issue, too.  It happened even when I reindex and wouldn't even pull in a single block.  Turned out to be a problem with the RPC connection to my coind.  Double check your RPC connections - even going as far as using a python client to make an RPC connection, and using the settings/credentials from the explorer.conf file.  I suspect you'll find a problem with port assignment, credentials, or firewall config.

**Comment by kepoly** [comment]
@rixon Thanks, you made me double check and I forgot to add the external wallet server to rpcallowip.
Indexing now.

**Comment by bitmoneygroup** [comment]
Here is the solution

https://github.com/iquidus/explorer/pull/67/files?diff=split

**Comment by olegmitrakhovich** [comment]
how do you add the "external wallet server" ?? @kepoly
