### ISSUE TITLE
Syncing at this rate takes months

### ISSUE THREAD

**Issue by koentjeappel** [iquidus/explorer#338]
I have tried it with a VPS with 4 cpu's 8 cpu's and it all kept going as quick as it is going now.

At the time of writing it is now at block 15216. It needs to go to block 386980.

Now i see that there are chains with blocks in the millions using this type of explorer how did they sync it?

At the moment it goes with 90 blocks in 20 seconds. 

https://i.gyazo.com/5b3c94a4322d48c1da2ab242e9bf1467.mp4

This is a video from the speed of transaction indexing.

Could someone help?

**Comment by uaktags** [comment]
A number of factors can lead to the slow sync:

- If on a version less than 1.6.2 then explorer was not coded for parallel sync and is missing a number of enhancements that were brought in recently.
- If you're on the recent version and your coind is running remotely, this can lead to latency between you and the RPC response
- If on the older version, the sync required to hit the /api of the explorer, which means you're also waiting on additional HTTP/TCP traffic to happen before even querying your coind. Newer versions we added "use_rpc" to bypass this /api and go directly towards hitting the coind's rpc.
- If you have a large number of txes per block, that'll severely slow you down.
- If you have a large number of vins and vouts (inputs/outputs) per tx per block
- If mongo is on a remote server or your server has slow I/O and write speeds, that'll slow down.


Probably the best way to really figure out how to help would be the following information:
Version of Iquidius, and what repo you obtained it from
Coin being sync'd
Is everything on the single VPS or are there any remote servers

**Comment by koentjeappel** [comment]
Thanks for your quick response! 

They are all on the same VPS, i started over today since it was at block 130k after almost a month of indexing. i saw that there were supposed to be improvements.

the version is Iquidus Explorer v1.7.3.

in the settings i have:
  //heavy (enable/disable additional heavy features)
  "heavy": false,

  //disable saving blocks & TXs via API during indexing.
  "lock_during_index": false,

Heavy, i didnt know what it does.

Also i put 
  // wallet settings
  "use_rpc": true,

i thought this would be the thing that allows for a direct RPC and not through the API.


this is a small part from forever running npm start:
[0mGET /ext/summary [36m304 [0m24.784 ms - -[0m
[0mGET /ext/getlasttxsajax/0?draw=10&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1578601327796 [32m200 [0m237.746 ms - 1964[0m
[0mGET /ext/summary [36m304 [0m19.722 ms - -[0m
[0mGET /ext/getlasttxsajax/0?draw=11&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1578601327797 [32m200 [0m301.790 ms - 1983[0m
[0mGET /ext/summary [36m304 [0m26.404 ms - -[0m
[0mGET /ext/getlasttxsajax/0?draw=12&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1578601327798 [32m200 [0m232.297 ms - 1990[0m
[0mGET /ext/summary [36m304 [0m15.535 ms - -[0m
[0mGET /ext/getlasttxsajax/0?draw=13&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1578601327799 [32m200 [0m462.325 ms - 1972[0m
[0mGET /api/getpeerinfo [32m200 [0m7.700 ms - 8163[0m
[0mGET /ext/summary [36m304 [0m16.552 ms - -[0m
[0mGET /ext/getlasttxsajax/0?draw=14&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1578601327800 [32m200 [0m328.477 ms - 1964[0m
[0mGET /ext/summary [36m304 [0m13.057 ms - -[0m
[0mGET /ext/getlasttxsajax/0?draw=15&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1578601327801 [32m200 [0m202.136 ms - 1947[0m
[0mGET /ext/summary [32m200 [0m25.629 ms - 159[0m
[0mGET /ext/getlasttxsajax/0?draw=16&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1578601327802 [32m200 [0m228.463 ms - 1971[0m
[0mGET /ext/summary [32m200 [0m63.031 ms - 159[0m
[0mGET /ext/getlasttxsajax/0?draw=17&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1578601327803 [32m200 [0m427.290 ms - 1964[0m
[0mGET /api/getpeerinfo [32m200 [0m5.606 ms - 8218[0m

I personally dont see a lot in this. 

thanks again

**Comment by uaktags** [comment]
Yep so that output is normal explorer output, unrelated to the sync process and instead related to the fact you're getting page loads on the explorer (or have just a single tab open with JavaScript doing it's normal table refreshes)

So that's good, if that's the output while indexing then you are definitely hitting RPC and bypassing /api.

Are you still slow as molasses now after the restart on the 1.7.3 codebase?

If no improvement, answer the other questions please and I'll do a test run myself.

**Comment by koentjeappel** [comment]
it is 100% quicker. am at 54k blocks now. So its quicker but still will take multiple days. Would be nice if it was quicker. 

It started way slower. probably because of more transactions there. wonder what would happen in the part where there were transaction attacks for like 10k blocks

**Comment by uaktags** [comment]
Yea I believe there could be one more setting the @TheHolyRoger built in with his update to add more tasks per run that may help. Have to take a look at settings.js for what it is.

**Comment by koentjeappel** [comment]
what i see in htop when i use an 8 core server is that every core is only getting used for like 10-20% and with a 4 core thats a bit more and with 2 core its at 60-60 %

maybe its a way to max out the cores while syncing?

**Comment by uaktags** [comment]
Check my edit above just in case you don't get a notification that I updated

**Comment by koentjeappel** [comment]
the thing is, im afraid that if it stop it it will need to go back from scratch

**Comment by koentjeappel** [comment]
okey i just did it, put the number on 6. but i feel like its skipping blocks. its going crazy fast.

https://i.gyazo.com/e7f52212f6d06b9ec75620f562ec03df.mp4

check this vid ^

and it is all while being at round 20-30% cpu usage. 

https://i.gyazo.com/edd9b7d51f9259a7cd3bfa04402e11b9.png


i feel like its skipping blocks or transactions or something

**Comment by uaktags** [comment]
In a way it is skipping, Basically that setting is saying that by default we only want 1 worker to work from 0 to blockheight (at the time of execution).
By changing it to 6, we have now set up 6 jobs where job 1 starts at block 1, job 2 at block 2, so on and so far, but they start at the same time and move up the blocks from there. so if Job2 has a block with say 10 transactions, and Job3 has a block with 4, then Job2 will finish and move on to the next block while Job1 is still working.

If you look at your video, and stop it, you'll see something like the following:

64987: txhash
64998: txhash
64997: txhash
64993: txhash
65000: txhash
64997: txhash
64999: txhash
64831: txhash
64993: txhash
65001: txhash

So if I was to guess and put this into perspective as to my first paragraph description:
JobA 64987: txhash
JobB 64998: txhash
JobC 64997: txhash
JobD 64993: txhash
JobE 65000: txhash
JobC 64997: txhash
JobF 64999: txhash
JobF 64831: txhash
JobA 64993: txhash
JobB 65001: txhash

Now obviously the order of which job is on which block is unimportant and just for illustration purposes. But this also shows us that JobF on block 64831 probably has a crap ton of txes (or that process is just severely behind) because it's still trucking through while the others are already moving up.

As for a test you can do to make sure nothing is being skipped:
My mongo is pretty shit but I'd presume it's something along the lines of "db.txes.distinct("blockindex")"
that'll give you from block 1 to the highest you have (you may need a .sort({ blockindex: -1}) to get it in order?
But anyway, that'll output each one. Then, you can either program a simple for-loop to scan over each on and see if anything is missing or put it into a spread sheet on column A, then do a 1 to highest number in column B, and ensure that they are even (look at the last number/row)

**Comment by koentjeappel** [comment]
Its going way faster now, when i check it in the browser i can see it all happening and it looks like it isnt skipping since they are all in the correct order. 

Thanks for the help!

**Comment by koentjeappel** [comment]
@uaktags I hope you are able to help or clear this up aswel. 

You can check on usa.pacglobalexplorer.com or on eu.pacglobalexplorer.com both instances indexing and both have their own node on their server. ( the EU one was set up when i opened this issue)

now they have gone from insanly fast to slow as a snail. This part has quite some transaction in them since there was a transaction attack going from block 140k to about 150k. 

at the moment i have set it on 10 "workers" in the settings and the CPU's on both machines are aroung 30-50%. 

Is there a way to do this part quicker? 

CPU usage: 
https://i.gyazo.com/d3df8eeb2430cf4f9150f5e24dee68c8.png

**Comment by uaktags** [comment]
I have PAC syncing now (1hr to go for the coind to be updated) just started iquidus.

**Comment by koentjeappel** [comment]
this really goes very slow, you can check on the websites

**Comment by uaktags** [comment]
So I've run into the same, removing the idea of your VPS being to culprit. I think it has to do with your coins allowance of these extremely low tx amounts. Some blocks have numerous txes and the txes are the same address but with what looks like dust amounts. So we're querying through, and have to calculate through it all which appears to be taxing. I havent yet broken this out to start echo'ing out where the bottleneck is, but I'm afraid I'm probably not going to be able to resolve this for the time being.

I'll keep a branch on my local running with pac for various testing in the meantime.

**Comment by koentjeappel** [comment]
Yeah, at that time there were "transaction attacks" where someone was spamming the chain and filling up the blocks.

**Comment by uaktags** [comment]
Fun stuff. It may be a point to look at to see what can be refactored in
our transaction calculations to speed up the process. Unfortunately it's
just going to have to wait at the moment I think. Let's get other updates
pushed, everything stable, and then try tuning.

**Comment by TheHolyRoger** [comment]
@koentjeappel you can try increasing this number https://github.com/iquidus/explorer/blob/master/lib/database.js#L790

But I'm 99% sure you'll end up with missing transactions/errors.

The save_tx logic is too complex to be combined into one mongo .aggregate call

**Comment by uaktags** [comment]
I'm in agreement, I went through and added some timers to see where the chugging and it's definitely within the sync over vin/vouts within save_tx.

```
150482: 22b3532c63da27688f88366c904df54f97d490707c59527517ab8ab7b1d5bf31
find tx:  a7f66c08b5a3390f3b8e50e98c819c24fe058687f0bd35d3985f8f61e0a6d230
save tx:  a7f66c08b5a3390f3b8e50e98c819c24fe058687f0bd35d3985f8f61e0a6d230
prepare vin a7f66c08b5a3390f3b8e50e98c819c24fe058687f0bd35d3985f8f61e0a6d230
prepare vout a7f66c08b5a3390f3b8e50e98c819c24fe058687f0bd35d3985f8f61e0a6d230
Elapsed:  2 seconds
sync loop over vin a7f66c08b5a3390f3b8e50e98c819c24fe058687f0bd35d3985f8f61e0a6d230 [ { addresses: 'PQjPFiHgMLeVxkVwSLHiNViScyCye2KpUR',
    amount: 60500 } ]
Elapsed:  0 seconds
sync loop over vout a7f66c08b5a3390f3b8e50e98c819c24fe058687f0bd35d3985f8f61e0a6d230 [ { addresses: 'PQjPFiHgMLeVxkVwSLHiNViScyCye2KpUR',
    amount: 44200 } ]
Time:  1579120431325 Elapsed:  2 seconds
Calculate Total a7f66c08b5a3390f3b8e50e98c819c24fe058687f0bd35d3985f8f61e0a6d230 [ { addresses: 'PQjPFiHgMLeVxkVwSLHiNViScyCye2KpUR',
    amount: 44200 } ]
Time:  1579120431.327 Elapsed:  2 seconds
Time Finished:  1579120431328 Elapsed:  2 seconds
```

**Comment by TheHolyRoger** [comment]
If we change the **prepare_vin** and **prepare_vout** functions to use objects rather than arrays and get rid of the expensive **is_unique** function it should speed this up quite dramatically.

**Comment by koentjeappel** [comment]
My indexing explorers are almost through that part :) So for me it wont change but would be cool if you guys could improve. 

nice that people are working on this explorer it looks good :)

**Comment by uaktags** [comment]
Yea, I think it'll be important to have, even for you, as who knows if a future update may (and it's likely to occur) require a reindex again. Atleast until some plan is formed how to check/repair a database. That'd be fun. haha.

On topic though, yea @TheHolyRoger this is where I started to really fumble at last year, trying to improve this save_tx as the main headache in use clustering in node. I'll have to find some old examples/trials I had.

**Comment by koentjeappel** [comment]
@uaktags @TheHolyRoger 

now it is past those slow blocks and went like a train. but now it ran into this error, which i cant find on the github:
/root/explorer/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'scriptPubKey' of undefined
    at /root/explorer/lib/explorer.js:523:19
    at Object.next (/root/explorer/lib/explorer.js:365:24)
    at Object.syncLoop (/root/explorer/lib/explorer.js:376:10)
    at Object.prepare_vout (/root/explorer/lib/explorer.js:497:20)
    at /root/explorer/lib/database.js:129:13
    at /root/explorer/lib/explorer.js:605:14
    at Object.next (/root/explorer/lib/explorer.js:365:24)
    at Object.syncLoop (/root/explorer/lib/explorer.js:376:10)
    at Object.prepare_vin (/root/explorer/lib/explorer.js:582:20)
    at /root/explorer/lib/database.js:128:11
    at /root/explorer/lib/explorer.js:207:16
    at Client.<anonymous> (/root/explorer/lib/explorer.js:29:14)
    at Client.tryCatcher (/root/explorer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter (/root/explorer/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/root/explorer/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/root/explorer/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/explorer/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/root/explorer/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/root/explorer/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/root/explorer/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/root/explorer/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/explorer/node_modules/bluebird/js/release/promise.js:649:10)

**Comment by TheHolyRoger** [comment]
@koentjeappel can you paste the block height or TX hash?

there's something weird going on in your vins somewhere

**Comment by koentjeappel** [comment]
You can check the explorer for info you might need on pacglobalexplorer.com

330.000 is the block we swapped from POW to POS.
________________________________

**Comment by TheHolyRoger** [comment]
@koentjeappel the problem transaction is this one:

https://pacglobalexplorer.com/api/getrawtransaction?txid=9d5e10d4bd2bc486b918a87019746c096d76cea4612e34eee228262ccafec28d&decrypt=1

It has no vin's or vout's... It's an easy fix, but I don't know the history of this TX?

What's the reason for no vins/vouts? Why does it have this "qcTx" attribute?

To fix: add a check for scriptPubKey https://github.com/iquidus/explorer/blob/master/lib/explorer.js#L523

`if (vout.length > 0 && vout[0].hasOwnProperty("scriptPubKey") && vout[0].scriptPubKey.type == 'nonstandard') {`

**Comment by koentjeappel** [comment]
I have no idea why that is, but will ask our dev

**Comment by koentjeappel** [comment]
{
  "txid": "9d5e10d4bd2bc486b918a87019746c096d76cea4612e34eee228262ccafec28d",
  "size": 342,
  "version": 3,
  "type": 6,
  "locktime": 0,
  "vin": [
  ],
  "vout": [
  ],
  "extraPayloadSize": 329,
  "extraPayload": "01002209050001000143d1ac7fa6984b5d9ff7051d001cb7f2d2b1abd6e8cdee990d90abe433f96e81320000000000000032000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "qcTx": {
    "version": 1,
    "height": 330018,
    "commitment": {
      "version": 1,
      "llmqType": 1,
      "quorumHash": "816ef933e4ab900d99eecde8d6abb1d2f2b71c001d05f79f5d4b98a67facd143",
      "signersCount": 0,
      "validMembersCount": 0,
      "quorumPublicKey": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "instantlock": false,
  "instantlock_internal": false,
  "chainlock": false
}

**Comment by koentjeappel** [comment]
with your fix it is syncing again, i added it wrong at first but after looking at it a couple of times, i saw what i did wrong and now its syncing

**Comment by koentjeappel** [comment]
But i see quite some 0 pac transactions, how would that be possible?

**Comment by koentjeappel** [comment]
Also if you look up that transaction on the main explorer it gives an error.

http://explorer.pacglobal.io/tx/9d5e10d4bd2bc486b918a87019746c096d76cea4612e34eee228262ccafec28d

**Comment by TheHolyRoger** [comment]
Yes, we need more information about what's going on with your chain in order to handle this

**Comment by koentjeappel** [comment]
I guess this is because of that, 

Since i compare 

https://eu.pacglobalexplorer.com/block/9ef64756b3f002169c33317bd4a49ce5ef78d0076cfb4da93df62e8690392e1a

and 

http://explorer.pacglobal.io/block-height/389237

it shows different values.

The value that is missing is the input split, when an input stakes it gets split up. and that is the part that is not showing

**Comment by uaktags** [comment]
Correct me if I'm completely wrong, but doesn't Iquidus not show stakes like this.

btc-rpc-explorer shows the raw breakdown of how things worked:
- An input was 9,232.9416278PAC that successfully staked
- 9,332.9416278PAC went back to the staker in two separate transactions (+100PAC total)
- 8,280PAC went to PQMcfSZAYH7sk1DKYHxeexyyynXKB8ka4b
- Total was 17,612.9416278PAC
- PQMcfSZAYH7sk1DKYHxeexyyynXKB8ka4b wallet balance went up 8280PAC
- PQKrXyrNdRpKu6YqDn1qjPXYmyoDyHQM78 wallet balance went up 100PAC.

https://eu.pacglobalexplorer.com/tx/1f21ee41503c1d7f493fc50044192884ce7062d758f99e72f558eccd00ed7dff
Iquidus on the other hand just shows the change in values during transactions (for better or worse?)
- An input was a PoS
- Output of 100PAC went to PQKrXyrNdRpKu6YqDn1qjPXYmyoDyHQM78 
- Output of 8280PAC went to PQMcfSZAYH7sk1DKYHxeexyyynXKB8ka4b 
- Total shown on the block is 8380PAC and # of Recipients are "2"

So, no issues in the end for balances, other than how it's shown to the word.

**Comment by TheHolyRoger** [comment]
Yeah iquidus by design has always simplified TX display to only show changes rather than all VINs/VOUTs (which are made available through the API).

The mysterious empty TXs with ZERO VINs/VOUTs are something else...

**Comment by TheHolyRoger** [comment]
@koentjeappel these are Quorum Commitment TXs (your coin is a fork of DASH).

Here's an example on DASH - I can't find any block explorers that show them correctly.

https://chainz.cryptoid.info/dash/tx.dws?ebcf4d5b223edd1ae1b1babf4f530aeefcf49b9bec00962c7f9b3f45b132d001.htm

**Comment by uaktags** [comment]
Yea, not crazy about those "nonstandard" txes, but that should be ignored. I've seen this occur a few times before, yet another headache of the dealing with good opensource communities that just do their own things. Even the RPC-Explorer can't decode these vins/vouts. There's also transactions where outputs appear burned due to "miners not claiming". 

I'd say there's probably not much we can really do for this though outside of just preforming a check against the tx. If there's no vin or vout just save the tx without it.

**Comment by uaktags** [comment]
I think for base functionality, we should just worry about coding around this idea of being able to save the transaction. 

Quorum/Masternodes/etc are all extras that I think would be a perfect discussion point for the future. This unfortunately would make Iquidus not a perfect solution for @koentjeappel  and PACGlobal/Dash forks, as it'd be missing some of these features for the time being, but we should first be a block explorer, get stable, refactor what we can, and then look at how to elegantly introduce additional features that can be enabled/disabled as needed based on the coin.

**Comment by koentjeappel** [comment]
Thanks for the help guys willl keep following iquidus!

I have also tried to get graviex market up but didnt manage. opened a issue on your github @uaktags where i found the graviex markets
