### ISSUE TITLE
sync.js crashes if tx is undefined

### ISSUE THREAD

**Issue by ucacoin** [iquidus/explorer#364]
We are using the explorer for our coin. The sync.js crashes if an empty tx is passed to syncloop.

```
explorer/lib/explorer.js:583
    module.exports.syncLoop(tx.vin.length, function (loop) {
                               ^

TypeError: Cannot read property 'vin' of undefined
    at Object.prepare_vin (/root/explorer/lib/explorer.js:583:32)
    at /root/explorer/lib/database.js:128:11
    at Request._callback (/root/explorer/lib/explorer.js:213:16)
    at self.callback (/root/explorer/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.onRequestError (/root/explorer/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:321:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

A simple if (tx) {} fixes that.

**Comment by uaktags** [comment]
Why would there be an empty tx?

**Comment by ucacoin** [comment]
I can't really tell you, we use a pivx based coin and we got this error while doing a reindex. So there seem to be some rare cases where the tx can be undefined.

**Comment by Hser2bio** [comment]
@ucacoin 

may be you need check if your coin are configured by pos in settings,conf 

and make a reindex

**Comment by justthedoctor** [comment]
I am having this same issue, if i sync.js index update, however if i reindex it works fine.

**Comment by TheHolyRoger** [comment]
Dup of #56
