### ISSUE TITLE
Error: Method not found     

### ISSUE THREAD

**Issue by k7n2g** [iquidus/explorer#381]
Hello can anyone help with this : Error solving and point me in the right direction please any help appreciated  

{ Error: Method not found
    at /root/explorer/node_modules/bitcoin/lib/jsonrpc.js:99:19
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/bitcoin/lib/jsonrpc.js:96:15)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: -32601 }
GET /api/masternode?command=count 200 4.818 ms - 39
{ Error: Method not found
    at /root/explorer/node_modules/bitcoin/lib/jsonrpc.js:99:19
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/bitcoin/lib/jsonrpc.js:96:15)
    at IncomingMessage.emit (events.js:187:15)

**Comment by dysoncoin** [comment]
have you already been able to solve the problem?
I have the same problem
