### ISSUE TITLE
no auth mechanism defined

### ISSUE THREAD

**Issue by k7n2g** [iquidus/explorer#385]
Solved last problem re installed now have this Error  anyone have a fix for this please

GET /api/getdifficulty 200 2.440 ms - 39
OperationalError: no auth mechanism defined
    at Auth.onRequest (/home/app/explorer/node_modules/request/lib/auth.js:132:32)
    at Request.auth (/home/app/explorer/node_modules/request/request.js:1341:14)
    at Request.init (/home/app/explorer/node_modules/request/request.js:378:10)
    at new Request (/home/app/explorer/node_modules/request/request.js:127:8)
    at request (/home/app/explorer/node_modules/request/index.js:53:10)
    at /home/app/explorer/node_modules/request/index.js:61:12
    at Object.apply (/home/app/explorer/node_modules/@uphold/request-logger/src/index.js:27:19)
    at Function.post (/home/app/explorer/node_modules/request/index.js:100:12)
    at Function.tryCatcher (/home/app/explorer/node_modules/bluebird/js/release/util.js:16:23)
    at Function.ret [as postAsync] (eval at makeNodePromisifiedEval (/home/app/explorer/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:12:23)

**Comment by k7n2g** [comment]
solved it with thanks to uaktags,  for those who may have this problem,  go to
settings.json
"wallet": {
    "host": "136.244.66.146",
    "port": 9333,
    "user": "xxxxxxxxxx",   Changeme to "username"
    "pass": "xxxxxxxxxxxx"Changeme to  "password"

DONE ERROR: fixed

**Comment by gdiscord** [comment]
This helped in my case too, thanks.

settings.json
"wallet": {
"host": "XX.XXX.XXX.XX",
"port": 9333,
**"user"**: "xxxxxxxxxx", Change "user" field to "username"
**"pass"**: "xxxxxxxxxxxx" Change "pass" field to "password"

The result should look like:
"wallet": {
"host": "XX.XXX.XXX.XX",
"port": 9333,
"username": "xxxxxxxxxx",
"password"**: "xxxxxxxxxxxx"
