### ISSUE TITLE
new CastError

### ISSUE THREAD

**Issue by k7n2g** [iquidus/explorer#386]
Hi everyone really need help with this error get it evertime i install iquidus
have followed all  issues suggestion and any help appreciated to solve this error 

script launched with pid: 24263
Error
    at new CastError (/home/app/explorer/node_modules/mongoose/lib/error/cast.js:18:16)
    at SchemaNumber.cast (/home/app/explorer/node_modules/mongoose/lib/schema/number.js:219:9)
    at SchemaNumber.castForQuery (/home/app/explorer/node_modules/mongoose/lib/schema/number.js:269:16)
    at Query._castUpdateVal (/home/app/explorer/node_modules/mongoose/lib/query.js:2394:17)
    at Query._walkUpdatePath (/home/app/explorer/node_modules/mongoose/lib/query.js:2342:25)
    at Query._castUpdate (/home/app/explorer/node_modules/mongoose/lib/query.js:2215:23)
    at Query.update (/home/app/explorer/node_modules/mongoose/lib/query.js:2046:22)
    at Function.update (/home/app/explorer/node_modules/mongoose/lib/model.js:1781:13)
    at /home/app/explorer/lib/database.js:814:17
    at Request._callback (/home/app/explorer/lib/explorer.js:135:18)
    at Request.self.callback (/home/app/explorer/node_modules/request/request.js:187:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/app/explorer/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/app/explorer/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:327:22) {
  message: 'Cast to number failed for value "There was an error. Check your console." at path "count"',
  kind: 'number',
  value: 'There was an error. Check your console.',
  path: 'count',
  reason: undefined
}
index cleared (reindex)
/home/app/explorer/lib/database.js:967
                            lib.syncLoop(block.tx.length, function (subloop) {
                                                  ^

TypeError: Cannot read property 'length' of undefined
    at /home/app/explorer/lib/database.js:967:51
    at Request._callback (/home/app/explorer/lib/explorer.js:214:16)
    at Request.self.callback (/home/app/explorer/node_modules/request/request.js:187:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/app/explorer/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/app/explorer/node_modules/request/request.js:965:12)

**Comment by GOSSIP-Blockchain** [comment]
Google for this: TypeError: Cannot read property 'length' of undefined

**Comment by TheHolyRoger** [comment]
Dup of #56
