### ISSUE TITLE
Installed and ran npm start. I got this error

### ISSUE THREAD

**Issue by saravana87** [iquidus/explorer#389]
I am new to installing the explorer. Can you please someone help on this.
THanks
> explorer@1.7.3 start /explo/explorer
> node --stack-size=10000 ./bin/cluster

internal/fs/utils.js:657
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (18730)
    at Object.writeFile (fs.js:1356:5)
    at Object.<anonymous> (/explo/explorer/bin/cluster:5:6)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! explorer@1.7.3 start: `node --stack-size=10000 ./bin/cluster`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the explorer@1.7.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-24T16_42_43_909Z-debug.log

**Comment by GOSSIP-Blockchain** [comment]
https://stakeandnodes.net/iquidus-explorer-installation-guide/

**Comment by saravana87** [comment]
> 
> 
> https://stakeandnodes.net/iquidus-explorer-installation-guide/

I downgraded the nodejs 14v to nodejs12 and it works.
Thanks for the link
