### ISSUE TITLE
ESOCKETTIMEDOUT Error while running index update

### ISSUE THREAD

**Issue by saravana87** [iquidus/explorer#390]
When I run the node scripts/sync.js index update I got the following error. It would be good if someone points me in the right direction.

**node scripts/sync.js index update**
script launched with pid: 13065
Error:  OperationalError: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/explo/explorer/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:299:28)
    at ClientRequest.emit (events.js:210:5)
    at Socket.emitRequestTimeout (_http_client.js:690:9)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:210:5)
    at Socket._onTimeout (net.js:469:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  cause: Error: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (/explo/explorer/node_modules/request/request.js:816:19)
      at Object.onceWrapper (events.js:299:28)
      at ClientRequest.emit (events.js:210:5)
      at Socket.emitRequestTimeout (_http_client.js:690:9)
      at Object.onceWrapper (events.js:299:28)
      at Socket.emit (events.js:210:5)
      at Socket._onTimeout (net.js:469:8)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7) {
    code: 'ESOCKETTIMEDOUT',
    connect: false
  },
  isOperational: true,
  code: 'ESOCKETTIMEDOUT',
  connect: false

**Comment by GOSSIP-Blockchain** [comment]
Looks like a problem with node. My suggestion for you, safe your config file and start over on a new installed machine with the guide which I sent you before.
