### ISSUE TITLE
Index stops working at block 46212

### ISSUE THREAD

**Issue by Betxoin** [iquidus/explorer#393]
Please help solve the problem.
Index stops working at block 46212.
index update, index check and index reindex do not solve the problem

http://209.250.243.8/

block 46212 has an unknown parameter
https://imgur.com/Qo97j7h

**Comment by uaktags** [comment]
Iquidus isn't built with an "unknown" parameter, and I am having a hard
time to think why your coin would have one too.

To fix would take an edit somewhere within the database.js for handling the
sync_tx loop.

**Comment by B1ackt34** [comment]
Hi, using explorer for Bitcoin Adult coin i'm having same problem at block 18100/18107

Here is the text in terminal

18100: 5f5c691751e56ab65bd89886b7a8f1a99a00519fa567bc684c5208281ad31e85
/root/explorer/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property '0' of undefined
    at /root/explorer/lib/explorer.js:503:74
    at Object.next (/root/explorer/lib/explorer.js:360:18)
    at Object.syncLoop (/root/explorer/lib/explorer.js:376:10)
    at Object.prepare_vout (/root/explorer/lib/explorer.js:497:20)
    at /root/explorer/lib/database.js:117:13
    at /root/explorer/lib/explorer.js:605:14
    at Object.next (/root/explorer/lib/explorer.js:365:24)
    at /root/explorer/lib/explorer.js:591:22
    at Object.convert_to_satoshi (/root/explorer/lib/explorer.js:40:12)
    at /root/explorer/lib/explorer.js:589:30
    at /root/explorer/lib/explorer.js:476:14
    at Object.next (/root/explorer/lib/explorer.js:365:24)
    at Object.syncLoop (/root/explorer/lib/explorer.js:376:10)
    at Object.is_unique (/root/explorer/lib/explorer.js:465:20)
    at /root/explorer/lib/explorer.js:587:26
    at /root/explorer/lib/explorer.js:571:20
    at Object.next (/root/explorer/lib/explorer.js:348:19)
    at /root/explorer/lib/explorer.js:565:22
    at Object.next (/root/explorer/lib/explorer.js:360:18)
    at Object.syncLoop (/root/explorer/lib/explorer.js:376:10)
    at /root/explorer/lib/explorer.js:557:26
    at /root/explorer/lib/explorer.js:207:16
