### ISSUE TITLE
the explorer closes when we use the search

### ISSUE THREAD

**Issue by luc1anocruz** [iquidus/explorer#414]
the explorer closes when we use the search. just click on Search and it closes instantly.

below the crash log...

GET /api/getblockhash?height= 200 2.677 ms - 74
POST /search 302 34.057 ms - 92
GET /api/getblock?hash=[object%20Object] 200 2.147 ms - 57
/explorer/lib/database.js:336
    lib.syncLoop(block.tx.length, function (loop) {
                          ^

TypeError: Cannot read property 'length' of undefined
    at Object.get_txs (/explorer/lib/database.js:336:27)
    at /explorer/routes/index.js:15:12
    at Request._callback (/explorer/lib/explorer.js:199:16)
    at Request.self.callback (/explorer/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/explorer/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/explorer/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by TheHolyRoger** [comment]
This looks like an issue with your coin RPC - can you please find this line:
https://github.com/iquidus/explorer/blob/master/routes/index.js#L15

```javascript
        db.get_txs(block, function(txs) {
```

and change to:

```javascript
        console.log(block);
        db.get_txs(block, function(txs) {
```

Then post the output here

**Comment by luc1anocruz** [comment]
yes,   how do I solve?  

{ message: 'Block not found', code: -5, name: 'RpcError' }
/explorer/lib/database.js:336
    lib.syncLoop(block.tx.length, function (loop) {

**Comment by luc1anocruz** [comment]
and when that happens, my index updates from the beginning, it doesn't start where it left off

**Comment by TheHolyRoger** [comment]
@luc1anocruz can you try changing `use_rpc` to true in your config? I think the error handling for the old method is broken but we were going to strip that out in the future anyway

**Comment by luc1anocruz** [comment]
resolved with use_rpc to true
