### ISSUE TITLE
Econnreset

### ISSUE THREAD

**Issue by grigzy28** [iquidus/explorer#433]
Just setup a new explorer, I have done a couple in the past, but I am getting this error message on the console.

I am using 1.7.4 with nodejs 12.20

The coin is 404

Any help would be appreciated.
Thanks
-------------------------------------
Error:  OperationalError: socket hang up
    at connResetException (internal/errors.js:609:14)
    at Socket.socketOnEnd (_http_client.js:458:23)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  cause: Error: socket hang up
      at connResetException (internal/errors.js:609:14)
      at Socket.socketOnEnd (_http_client.js:458:23)
      at Socket.emit (events.js:326:22)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'ECONNRESET'
  },
  isOperational: true,
  code: 'ECONNRESET'
}
---------------------------------

**Comment by grigzy28** [comment]
Okay, got this one figured out, the RPC port 31667 it didn't like changed to 31668 and it started working.  Now a new issue has cropped up and will open a new issue.
