### ISSUE TITLE
TypeError: Cannot read property 'success' of undefined

### ISSUE THREAD

**Issue by vkcoin** [iquidus/explorer#44]
c:\explorer\lib\markets\cryptsy.js:45
    if (body.success == true) {

TypeError: Cannot read property 'success' of undefined
    at Request._callback (c:\explorer\lib\markets\cryptsy.js:45:13)
    at self.callback (c:\explorer\node_modules\request\request.js:121:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.self.clientErrorHandler (c:\explorer\node_modules\request\r
equest.js:230:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at connectErrorNT (net.js:996:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

got this error when run:
*/2 * * * * cd /path/to/explorer && /usr/bin/node scripts/sync.js market

**Comment by iquidus** [comment]
should be fixed in master branch now
