### ISSUE TITLE
RPC Error when launching first time

### ISSUE THREAD

**Issue by dlsnow** [iquidus/explorer#473]
GET /ext/getlasttxsajax/0?draw=[REDACTED LOTS OF STUFF HERE] 200 3.535 ms - 59
GET /ext/summary - - ms - -
Error:  RpcError: Unauthorized
    at Client.rpc (/root/explorer2/node_modules/bitcoin-core/dist/src/parser.js:73:13)
    at Client.tryCatcher (/root/explorer2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/explorer2/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/explorer2/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/explorer2/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/explorer2/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/root/explorer2/node_modules/bluebird/js/release/promise.js:673:18)
    at Request._callback (/root/explorer2/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/root/explorer2/node_modules/request/request.js:185:22)
    at Request.emit (events.js:215:7)
    at Request.<anonymous> (/root/explorer2/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/root/explorer2/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  message: 'Unauthorized',
  body: '',
  code: 401,
  name: 'RpcError'

**Comment by dlsnow** [comment]
Disregard - it was a mismatch in RPC config/SMH
