### ISSUE TITLE
richlist chart 

### ISSUE THREAD

**Issue by F3nixsec** [iquidus/explorer#488]
have a error in google chrome console 
Uncaught ReferenceError: pieWealthDist is not defined
    at richlist:79:3
    at dispatch (jquery.min.js:3:8066)
    at r.handle (jquery.min.js:3:4767)

and distribution in chart dont  work

**Comment by joeuhren** [comment]
A pull request was added 4 years ago that fixes this error by moving the window resize function into the document.ready scope. For some reason it was closed and never merged into the main source. To be honest, I think an easier fix would be to just remove the whole window resize function altogether because replotting the pie chart on window resize seems to do nothing anyway and is probably unnecessary.

[https://github.com/iquidus/explorer/pull/155/files](https://github.com/iquidus/explorer/pull/155/files)

**Comment by uaktags** [comment]
Looks like the author of that PR closed it himself.
I don't think we have the ``.resizable`` parameter set on the pieWealthDist, so I both agree that its probably useless having the variable on the window resize. If we added the resizable, i'd change up the (window).resize and instead just bind it to the event or to the window.onresize and add proper error checking for the variable.

jqPlot is also extremely outdated, and could probably be due for an upgrade to something like chart.js or something else.
