### ISSUE TITLE
Explorer working but nothing showing up

### ISSUE THREAD

**Issue by violetdroidxz** [iquidus/explorer#503]
Hi there...I successfully install explorer and working also I tried many commands for sync,update,check,reindex and index ...
Whenever I run the command I'm getting this error : 

Error:  { Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  cause: { Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9) code: 'ECONNRESET' },
  isOperational: true,
  code: 'ECONNRESET' }
Error:  { Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  cause: { Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9) code: 'ECONNRESET' },
  isOperational: true,
  code: 'ECONNRESET' }

SOMEBODY HELP ME!!! :\  
I'm sure ...this error is creating issue that is why blockchain table and stats are BLANK

**Comment by joeuhren** [comment]
Searching through the closed issues here brings up multiple matches for the same error and in all cases the problem ended up being that the rpc port configured in the explorer is either incorrect or another app is already using the port:

#433 
#398 
#205 
#184 

Double-check what rpc port your coin is using and also make sure you aren't overriding it in the coin config file. Then make sure you set the same port in the settings.json file in this section:

```
  "wallet": {
    "host": "localhost",
    "port": 9332,
    "username": "darkcoinrpc",
    "password": "123gfjk3R3pCCVjHtbRde2s5kzdf233sa"
  },
```

Be sure you aren't trying to use the coins p2p port as that will not work. It must be the rpc port.

**Comment by uaktags** [comment]
this issue was also related to #504 and #501

**Comment by uaktags** [comment]
Closing, as the OP found out, if you set your config to match what you need to for your coin daemon, it works.
