### ISSUE TITLE
Can't install the explorer, Node deprecated packages

### ISSUE THREAD

**Issue by getbitcoinx** [iquidus/explorer#514]
npm install --production
npm http GET https://registry.npmjs.org/bitcoin-core/2.0.0
npm http 200 https://registry.npmjs.org/bitcoin-core/2.0.0
npm http GET https://registry.npmjs.org/bitcoin-core/-/bitcoin-core-2.0.0.tgz
npm http 200 https://registry.npmjs.org/bitcoin-core/-/bitcoin-core-2.0.0.tgz
npm WARN engine bitcoin-core@2.0.0: wanted: {"node":">=4"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm http GET https://registry.npmjs.org/debugnyan
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/json-bigint
npm http GET https://registry.npmjs.org/uphold/request-logger
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/standard-error
npm http GET https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/lodash
npm http 405 https://registry.npmjs.org/uphold/request-logger
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/home/x/.nvm/v0.10.25/lib/node_modules/npm/lib/cache.js:692:35)
npm ERR!     at /home/x/.nvm/v0.10.25/lib/node_modules/npm/lib/cache.js:680:5
npm ERR!     at saved (/home/x/.nvm/v0.10.25/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /home/x/.nvm/v0.10.25/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 5.15.0-91-generic
npm ERR! command "/home/x/.nvm/v0.10.25/bin/node" "/home/x/.nvm/v0.10.25/bin/npm" "install" "--production"
npm ERR! cwd /home/x/Documents/explorer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! type non_object_property_load
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/json-bigint
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/debugnyan
npm http 304 https://registry.npmjs.org/standard-error
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/x/Documents/explorer/npm-debug.log
npm ERR! not ok code 0

**Comment by joeuhren** [comment]
According to your log, you're using a very old version of node.js. It's asking you to install at least v4 and you currently have v0 installed. Use `nvm` to install whatever version of nodejs you want, something more modern and try the setup again
