### ISSUE TITLE
Error in scripts/sync.js on zcash coin

### ISSUE THREAD

**Issue by baldpope** [iquidus/explorer#60]
Setting up a new explorer session to read ZCash block chain.  Most everything has gone well, but recieving the following error on block 396 (each and every time)

/opt/zcash_explorer/explorer$ /usr/local/bin/node scripts/sync.js index check
script launched with pid: 5609

TypeError: Cannot read property 'scriptPubKey' of undefined
    at /opt/zcash_explorer/explorer/lib/explorer.js:310:18
    at Object.loop.next (/opt/zcash_explorer/explorer/lib/explorer.js:194:24)
    at Object.module.exports.syncLoop (/opt/zcash_explorer/explorer/lib/explorer.js:205:10)
    at Object.module.exports.prepare_vout (/opt/zcash_explorer/explorer/lib/explorer.js:284:20)
    at /opt/zcash_explorer/explorer/lib/database.js:141:17
    at /opt/zcash_explorer/explorer/lib/explorer.js:392:14
    at Object.loop.next (/opt/zcash_explorer/explorer/lib/explorer.js:194:24)
    at /opt/zcash_explorer/explorer/lib/explorer.js:378:22
    at Object.module.exports.convert_to_satoshi (/opt/zcash_explorer/explorer/lib/explorer.js:25:12)
    at /opt/zcash_explorer/explorer/lib/explorer.js:376:30
    at /opt/zcash_explorer/explorer/lib/explorer.js:263:14
    at Object.loop.next (/opt/zcash_explorer/explorer/lib/explorer.js:194:24)
    at Object.module.exports.syncLoop (/opt/zcash_explorer/explorer/lib/explorer.js:205:10)
    at Object.module.exports.is_unique (/opt/zcash_explorer/explorer/lib/explorer.js:252:20)
    at /opt/zcash_explorer/explorer/lib/explorer.js:374:26
    at /opt/zcash_explorer/explorer/lib/explorer.js:358:20

**Comment by baldpope** [comment]
Is it possibly erroring out because there are too many transactions tied to this particular block?  I bumped the TX in settings.json and it's now showing 400.  Going to bump this number again and re-run.  Any thoughts would be greatly appreciated though.

**Comment by baldpope** [comment]
no luck, only other error is this:

/usr/local/bin/node scripts/sync.js index update
script launched with pid: 5754
tx not found: c4eaa58879081de3c24a7b117ed2b28300e7ec4c4c1dff1d3f1268b7857a4ddb

Continues to die on block 396.

**Comment by aayanl** [comment]
Block 396 is where the first joinsplit happened

**Comment by cryptorex** [comment]
was this ever fixed, if so, how?

**Comment by DeckerSU** [comment]
@baldpope , @cryptorex Try to use [this fix](https://github.com/DeckerSU/explorer/commit/ac74e41c6162871fcaa6973d34f09f1cf3e5a1ce) .

**Comment by cryptorex** [comment]
thanks for responding @DeckerSU I used this https://github.com/cryptorex/bitcoinz-explorer/commit/267a0dfd8015bc90488b2b53ae9c49be2da83bff

**Comment by TheHolyRoger** [comment]
Dup of https://github.com/iquidus/explorer/issues/56
