### ISSUE TITLE
Getting errors during initial sync/update 

### ISSUE THREAD

**Issue by maxya** [iquidus/explorer#72]
Installed iquidus following instructions, the initial sync with update or node scripts/sync.js index reindex goes upto 99003 then it crashed with the following error: 
```
99001: 9b1e39a057171876efe58c724cea6647f7636321a4c759f78e902f2dedd39d6d
99001: f87764f65dd741846227560c2004a6a24f04149b7b45d5d3f6c41d787e294bbe
99002: 094387d64c2d5ade58045031497fd1b908e18bbdad12a582e5a2f5d855e4ac08
99002: 19cf2b432f780e3832920013ac6b0cee204b877b795186462ee557ebd688b898
99002: 5381e0af493bc3bd983579aff3c222d9f7bedb2f5b51735b74c910127bf0b264
99002: 06bcb71fd45d0b60129313d0b47a8c6c086246cb9ba0dc110a6d854bf1d0866c
99002: 140bfd36dfba3da9c62b6ca1c4071710c8b287506ff682898f1e429026bb41b5
99002: 379975e30beae9b8bb3a253a88303057da9ef46df56796c9ca35d8f8caa65893
99002: 69fd8b734c7941f3d73899845fab143676969acf611d43cc5c9e1f5288b86441
99003: a68b1eb7452ad7ee9434ff657d5469e28578df429ec42cf1edc41922fb7f15e6
99003: c0f6db26f295302e7f63c522a7b30fc2ddefb2a0eba8e4e96f002d926e510c1f
/home/maxim/explorer/lib/explorer.js:252
    module.exports.syncLoop(array.length, function (loop) {
                                                   ^

RangeError: Maximum call stack size exceeded
    at /home/maxim/explorer/lib/explorer.js:252:52
    at Object.next (/home/maxim/explorer/lib/explorer.js:189:18)
    at /home/maxim/explorer/lib/explorer.js:260:14
    at Object.next (/home/maxim/explorer/lib/explorer.js:189:18)
    at /home/maxim/explorer/lib/explorer.js:260:14
    at Object.next (/home/maxim/explorer/lib/explorer.js:189:18)
    at /home/maxim/explorer/lib/explorer.js:260:14
    at Object.next (/home/maxim/explorer/lib/explorer.js:189:18)
    at /home/maxim/explorer/lib/explorer.js:260:14
    at Object.next (/home/maxim/explorer/lib/explorer.js:189:18)
    at /home/maxim/explorer/lib/explorer.js:260:14
    at Object.next (/home/maxim/explorer/lib/explorer.js:189:18)
    at /home/maxim/explorer/lib/explorer.js:260:14
    at Object.next (/home/maxim/explorer/lib/explorer.js:189:18)
    at /home/maxim/explorer/lib/explorer.js:260:14
    at Object.next (/home/maxim/explorer/lib/explorer.js:189:18)
```
Please advice. 
Thank you

**Comment by maxya** [comment]
Changing `"txcount": 10,` from default 100 seems like fixed the issue, I've past dec 2010 mark and still syncing.  Will see if it can complete sync.
Thanks

**Comment by mdrankin** [comment]
Getting the same issue. Changing the txcount from 100 to 10 has made no difference.

**Comment by Hser2bio** [comment]
node --stack-size=20000 scripts/sync.js index update
