### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by nipfip** [iquidus/explorer#79]
Trying to implant a block explorer for a new altcoin(Credits) and I am getting the following error when trying to run my first initial sync.

```
script launched with pid: 30836
/etc/explorer/lib/database.js:642
              lib.syncLoop(block.tx.length, function (subloop) {
                                   ^

TypeError: Cannot read property 'length' of undefined
    at /etc/explorer/lib/database.js:642:36
    at Request._callback (/etc/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/etc/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/etc/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/etc/explorer/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)

```

**Comment by nipfip** [comment]
Figured out that the script couldn't use the default RPC port some weird reason.

**Comment by perfectnihil** [comment]
@nipfip  could you give any detail how to solve this issue?
