### ISSUE TITLE
Cron Error sync.js index update

### ISSUE THREAD

**Issue by theflu** [iquidus/explorer#83]
Coin: chaincoin
OS: Ubuntu 14.04

```
/home/chcuser/explorer/lib/explorer.js:252
    module.exports.syncLoop(array.length, function (loop) {
                                                   ^

RangeError: Maximum call stack size exceeded
    at /home/chcuser/explorer/lib/explorer.js:252:52
    at Object.next (/home/chcuser/explorer/lib/explorer.js:189:18)
    at /home/chcuser/explorer/lib/explorer.js:260:14
    at Object.next (/home/chcuser/explorer/lib/explorer.js:189:18)
    at /home/chcuser/explorer/lib/explorer.js:260:14
    at Object.next (/home/chcuser/explorer/lib/explorer.js:189:18)
    at /home/chcuser/explorer/lib/explorer.js:260:14
    at Object.next (/home/chcuser/explorer/lib/explorer.js:189:18)
    at /home/chcuser/explorer/lib/explorer.js:260:14
    at Object.next (/home/chcuser/explorer/lib/explorer.js:189:18)
    at /home/chcuser/explorer/lib/explorer.js:260:14
    at Object.next (/home/chcuser/explorer/lib/explorer.js:189:18)
    at /home/chcuser/explorer/lib/explorer.js:260:14
    at Object.next (/home/chcuser/explorer/lib/explorer.js:189:18)
    at Object.syncLoop (/home/chcuser/explorer/lib/explorer.js:205:10)
    at Object.is_unique (/home/chcuser/explorer/lib/explorer.js:252:20)
```

**Comment by theflu** [comment]
When this happens the PID file is not removed so the script thinks its already running. A better way to do this would be to take the PID and see if there is something running with that PID and if not remove the file and continue running.

**Comment by theflu** [comment]
I have created a bash script to do this before the script is launched

```
#!/bin/bash

file="/home/chcuser/explorer/tmp/index.pid" #the file where you keep your string name

name=$(cat "$file")

if [ -z "${kpid}" -a -d "/proc/${kpid}" ]
  then
    rm /home/chcuser/explorer/tmp/index.pid
fi
```
and changed my cron to this
```
* * * * * cd /home/chcuser/explorer && ./scripts/pidcheck.sh && /usr/bin/nodejs scripts/sync.js index update > /dev/null 2>&1
```

**Comment by mddeepak** [comment]
node scripts/sync.js index update
script launched with pid: 6952
C:\explorer\explorer\lib\database.js:642
              lib.syncLoop(block.tx.length, function (subloop) {
                                    ^

TypeError: Cannot read property 'length' of undefined
    at C:\explorer\explorer\lib\database.js:642:37
    at Request._callback (C:\explorer\explorer\lib\explorer.js:107:14)
    at Request.self.callback (C:\explorer\explorer\node_modules\request\request.
js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\explorer\explorer\node_modules\request\request.js
:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\explorer\explorer\node_modules\request\re
quest.js:965:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

please give me any solution.

**Comment by TheHolyRoger** [comment]
Dup of https://github.com/iquidus/explorer/issues/56
